### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by silvershort** [devmemory/kakaomap_webview#13]
### 빌드 환경
Window10
AndroidStudio Chipmunk 2021.2.1 patch 1
플러터 3.0.2
다트 2.17.3

### 에러 증상

![이미지 001](https://user-images.githubusercontent.com/57101477/173528980-9acfaf49-7484-45bb-907a-2b1d76fff0a1.png)

pub에 있는 위젯 샘플코드를 그대로 썼을때 카카오맵이 출력되지 않고

Null check operator used on a null value 에러 문구가 적혀있고 세로 길이가 무한한 빨간 네모 위젯이 출력됩니다.

라이브러리 버전을 0.5.0으로 낮출경우 해당 현상이 발생하지 않는데 최신버전 사용했을때 문제되는 사항이 있을까요?...

- 에러로그

```
The following _CastError was thrown building KakaoMapView(dirty):
Null check operator used on a null value

The relevant error-causing widget was: 
 KakaoMapView KakaoMapView:file:///C:/Users/username/Documents/flutter_example/appname/lib/view/detail_view.dart:112:11
When the exception was thrown, this was the stack: 
#0      KakaoMapView._getHTML (package:kakaomap_webview/src/kakaomap_view.dart:300:38)
#1      KakaoMapView.build (package:kakaomap_webview/src/kakaomap_view.dart:122:46)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:4876:49)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#8      MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#9      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (16 frames)
#25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#26     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#27     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (4 frames)
#31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3545:20)
#33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#44     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#46     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#52     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#54     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#57     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#58     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#60     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#62     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#64     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#67     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#68     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#71     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#73     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#76     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#77     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#78     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#81     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#82     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#86     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#89     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#90     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#93     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#94     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#95     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#97     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#98     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#99     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#100    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5825:32)
#101    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#102    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#104    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#105    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#106    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#107    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#109    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#110    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#111    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#113    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#114    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#115    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#117    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#120    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#121    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#123    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#126    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#127    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#128    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#129    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#131    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#132    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#133    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#134    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#136    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#137    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#138    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#139    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#140    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#141    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#142    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#143    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#144    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#145    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#146    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#147    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#148    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#149    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#150    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#151    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#153    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#154    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#155    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#156    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#158    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#159    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#160    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#161    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
#162    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#163    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#164    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#165    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#169    _invoke (dart:ui/hooks.dart:151:10)
#170    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#171    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================
D/EGL_emulation(16029): app_time_stats: avg=12369.21ms min=3.14ms max=185187.11ms count=15
```

**Comment by devmemory** [comment]
같은 환경에서 테스트 해봤는데, 정상작동 합니다
https://pub.dev/packages/kakaomap_webview/example
그대로 사용했습니다

코드 공유해주시면 한번 봐드리겠습니다

**Comment by silvershort** [comment]
저도 방금 테스트 해보니까 Example 코드로 했을때는 정상출력이 되는것을 확인했습니다 !

플러터 입문한지가 얼마 안되서 pub에 Readme만 생각하고 Example 탭이 있다는걸 생각못하고 있었습니다 ㅠ...
질문에서 샘플코드를 그대로 사용했다고 해버려서 혼동을 드린것같네요.

제가 시도했던건 Readme에 있는 1. When you want to use as Widget 스니펫을 사용해서 지도화면을 출력하는거였습니다.
아래 코드를 썼을때 0.5.0는 정상출력되고 0.6.0은 에러가 발생합니다.


```
import 'package:flutter/material.dart';
import 'package:kakaomap_webview/kakaomap_webview.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("타이틀"),
      ),
      body: Column(
        children: [
          KakaoMapView(
          width: 300,
          height: 400,
          kakaoMapKey: "apikey",
          lat: 33.450701,
          lng: 126.570667,
          showMapTypeControl: true,
          showZoomControl: true,
          markerImageURL: 'https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/marker_red.png',
          onTapMarker: (message) {
            //event callback when the marker is tapped
          }),
        ],
      ),
    );
  }
}
```

**Comment by devmemory** [comment]
0.6.0 버전에서 제가 체크 못한 부분이 있었네요..
일단 수정해서 0.6.1 버전 배포 했습니다 :)

**Comment by silvershort** [comment]
확인해봤는데 mapType도 required 파라미터가 아닌데 NonNull로 사용하고 있어서 0.6.1에서 똑같은 에러가 발생합니다!

**Comment by devmemory** [comment]
그 부분은 체크를 못했네요..
해당 부분도 수정해서 배포했습니다
테스트 감사드립니다.. ( _ _ )

**Comment by silvershort** [comment]
정상작동 확인했습니다 빠른수정 감사합니다 !
